In [25]:
from bs4 import BeautifulSoup as bs
from selenium import webdriver
import pandas as pd

path="c:\python_temp\chromedriver.exe"
driver=webdriver.Chrome(path)
driver.get("https://finance.daum.net/")
driver.maximize_window()
driver.find_element_by_xpath('//*[@id="boxMarketTrend"]/div[2]/ul/li[2]/a').click()
driver.find_element_by_xpath('//*[@id="boxMarketTrend"]/div[2]/ul/li[3]/a').click()
driver.find_element_by_xpath('//*[@id="boxMarketTrend"]/div[2]/ul/li[4]/a').click()
driver.find_element_by_xpath('//*[@id="boxMarketTrend"]/div[2]/ul/li[5]/a').click()
driver.find_element_by_xpath('//*[@id="boxMarketTrend"]/div[2]/ul/li[6]/a').click()

In [27]:
html=driver.page_source
soup=bs(html,'html.parser')
ranks=soup.find_all('div',class_="halfB")
def section_tap():
    kotitle=[]
    konum=[1,2,3,4,5]
    kosection=[]
    koupdown=[]
    koname=[]
    for i in ranks[1:3]:
        kotitle.append(i.select('h4')[0].text)
        section=(i.select('a'))[1::2]
        for j in section:
            kosection.append(j.text)
        name=(i.select('a'))[2::2]
        for k in name:
            koname.append(k.text.replace('\n',"").replace(" ","").replace("▲",""))
        updown=(i.select('span'))
        for l in updown:
            koupdown.append(l.text)
    print(kotitle)
    print(kosection)
    print(koname)
    print(koupdown)
    
    list=[]
    for i in range(10):
        list.append([kosection[i],koname[i],koupdown[i]])
    kospi=pd.DataFrame(list[0:5], columns=['업종','종목','등락'], index=konum)
    kosdak=pd.DataFrame(list[5:], columns=['업종','종목','등락'], index=konum)
    print()
    print(kotitle[0])
    print(kospi)
    print()
    print(kotitle[1])
    print(kosdak)
    
    return kospi
def rank():
    section_rank={'업종코스피':kospi,'업종코스닥':kosdak}
    what=input("")
    return section_rank[what] 
section_tap()

['업종 상위 - 코스피', '업종 상위 - 코스닥']
['철강금속', '의약품', '운수장비', '섬유의복', '화학', '운송장비·부품', '종이·목재', '일반전기전자', '유통', '방송서비스']
['동일산업', '대원제약', '일진하이솔루스', '대한방직', 'SK케미칼우', '세원', '동화기업', '상신전자', '바른손', '티비씨']
['+1.89%', '+1.72%', '+1.66%', '+1.31%', '+1.01%', '+2.85%', '+2.75%', '+1.86%', '+1.69%', '+1.47%']

업종 상위 - 코스피
     업종       종목      등락
1  철강금속     동일산업  +1.89%
2   의약품     대원제약  +1.72%
3  운수장비  일진하이솔루스  +1.66%
4  섬유의복     대한방직  +1.31%
5    화학   SK케미칼우  +1.01%

업종 상위 - 코스닥
        업종    종목      등락
1  운송장비·부품    세원  +2.85%
2    종이·목재  동화기업  +2.75%
3   일반전기전자  상신전자  +1.86%
4       유통   바른손  +1.69%
5    방송서비스   티비씨  +1.47%

     업종       종목      등락
1  철강금속     동일산업  +1.89%
2   의약품     대원제약  +1.72%
3  운수장비  일진하이솔루스  +1.66%
4  섬유의복     대한방직  +1.31%
5    화학   SK케미칼우  +1.01%

In [26]:
html=driver.page_source
soup=bs(html,'html.parser')
ranks=soup.find_all('div',class_="halfB")
def market_trend():
    
    kos=['코스피','코스닥']
    num=[1,2,3,4,5]
    for i in ranks[3:]:
        if i in ranks[7:11]:
            m_name=[]
            m_price=[]
            m_amount=[]
            m_updown=[]
            name=(i.select_one('ul').select('a'))
            updown=(i.select_one('ul').select('span')[1::2])
            amount=(i.select_one('ul').select('span')[0::2])
            price=(i.select_one('ul').select('p'))
            for a in name:
                m_name.append(a.text)
            for s in updown:
                m_updown.append(s.text)
            for d in amount:
                m_amount.append(d.text+',000')
            for f in price:
                m_price.append(f.text+',000,000원')
            list=[]
            for i in range(5):
                list.append([m_name[i],m_updown[i],m_amount[i],m_price[i]])
            print(m_name)
            print(m_updown)
            print(m_amount)
            print(m_price)
            print()
            chart=pd.DataFrame(list,columns=['종목','등락률','총 거래량','총 거래액'],index=num)
            print(chart)
            print('*'*80)
        else:
            m_name=[]
            m_price=[]
            m_udprice=[]
            m_updown=[]
            m_amount=[]
            item=(i.select('ul')[0].select('a'))
            price=(i.select('ul')[0].select('p')[0::2])
            amount=(i.select('ul')[0].select('p')[1::2])
            udprice=(i.select('ul')[0].select('span')[0::2])
            updown=(i.select('ul')[0].select('span')[1::2])
            for j in item:
                m_name.append(j.text)
            for k in price:
                m_price.append(k.text)
            for l in amount:
                m_amount.append(l.text)
            for q in udprice:
                m_udprice.append(q.text)
            for w in updown:
                m_updown.append(w.text)

            print(m_name)
            print(m_price)
            print(m_amount)
            print(m_udprice)
            print(m_updown)
            list=[]
            for i in range(5):
                list.append([m_name[i],m_price[i],m_udprice[i],m_updown[i],m_amount[i]])
            chart=pd.DataFrame(list,num,['종목','가격','등락가격','등락률','거래량'])
            print()
            print(chart)
            print('*'*80)
market_trend()

['우신시스템', '일진하이솔루스', 'SK케미칼우', '넥스트사이언스', '에스엘']
['7,140', '71,300', '177,000', '27,500', '30,900']
['21,299,615', '986,848', '178,688', '1,329,146', '559,176']
['▲1,360', '▲10,200', '▲24,500', '▲3,050', '▲2,850']
['+23.53%', '+16.69%', '+16.07%', '+12.47%', '+10.16%']

        종목       가격     등락가격      등락률         거래량
1    우신시스템    7,140   ▲1,360  +23.53%  21,299,615
2  일진하이솔루스   71,300  ▲10,200  +16.69%     986,848
3   SK케미칼우  177,000  ▲24,500  +16.07%     178,688
4  넥스트사이언스   27,500   ▲3,050  +12.47%   1,329,146
5      에스엘   30,900   ▲2,850  +10.16%     559,176
********************************************************************************
['바른손', '지더블유바이텍', '엔피케이', '디에이테크놀로지', '티비씨']
['4,495', '2,695', '2,295', '7,070', '2,225']
['23,737,884', '774,116', '5,066,628', '9,719,287', '48,130,262']
['▲785', '▲455', '▲320', '▲860', '▲290']
['+21.16%', '+20.31%', '+16.20%', '+13.85%', '+14.99%']

         종목     가격  등락가격      등락률         거래량
1       바른손  4,495  ▲785  +21.16%  23,737,884
2   지더블유바이텍  2,695  ▲455  +20.31%     774,116
3      엔피케이  2,295  ▲320  +16.20%   5,066,628
4  디에이테크놀로지  7,070  ▲860  +13.85%   9,719,287
5       티비씨  2,225  ▲290  +14.99%  48,130,262
********************************************************************************
['대신 인버스 2X 니켈선물 ETN(H)', '신원', '포스코케미칼', '세우글로벌', '아시아나항공']
['3,650', '2,675', '151,000', '3,145', '23,700']
['6,297', '7,956,213', '1,180,932', '1,574,416', '1,144,826']
['▼370', '▼230', '▼12,500', '▼195', '▼1,400']
['-9.20%', '-7.92%', '-7.65%', '-5.84%', '-5.58%']

                      종목       가격     등락가격     등락률        거래량
1  대신 인버스 2X 니켈선물 ETN(H)    3,650     ▼370  -9.20%      6,297
2                     신원    2,675     ▼230  -7.92%  7,956,213
3                 포스코케미칼  151,000  ▼12,500  -7.65%  1,180,932
4                  세우글로벌    3,145     ▼195  -5.84%  1,574,416
5                 아시아나항공   23,700   ▼1,400  -5.58%  1,144,826
********************************************************************************
['이더블유케이', '씨유테크', '대유', '국전약품', '엘아이에스']
['6,190', '9,340', '5,620', '12,300', '5,430']
['917,730', '8,734,525', '946,218', '3,513,328', '189,291']
['▼1,790', '▼2,660', '▼1,120', '▼1,950', '▼860']
['-22.43%', '-22.17%', '-16.62%', '-13.68%', '-13.67%']

       종목      가격    등락가격      등락률        거래량
1  이더블유케이   6,190  ▼1,790  -22.43%    917,730
2    씨유테크   9,340  ▼2,660  -22.17%  8,734,525
3      대유   5,620  ▼1,120  -16.62%    946,218
4    국전약품  12,300  ▼1,950  -13.68%  3,513,328
5   엘아이에스   5,430    ▼860  -13.67%    189,291
********************************************************************************
['기아', 'SK바이오사이언스', '한국가스공사', '일진머티리얼즈', 'SK케미칼']
['+2.63%', '+0.22%', '-0.63%', '+3.96%', '+4.97%']
['280,000', '92,000', '424,000', '198,000', '59,000']
['21,734,000,000원', '21,037,000,000원', '19,831,000,000원', '19,637,000,000원', '16,751,000,000원']

          종목     등락률    총 거래량            총 거래액
1         기아  +2.63%  280,000  21,734,000,000원
2  SK바이오사이언스  +0.22%   92,000  21,037,000,000원
3     한국가스공사  -0.63%  424,000  19,831,000,000원
4    일진머티리얼즈  +3.96%  198,000  19,637,000,000원
5      SK케미칼  +4.97%   59,000  16,751,000,000원
********************************************************************************
['엘앤에프', '에코프로비엠', '셀트리온제약', '네이처셀', '티케이케미칼']
['+6.01%', '+4.96%', '+3.69%', '-8.60%', '-2.92%']
['130,000', '28,000', '67,000', '326,000', '999,000']
['21,557,000,000원', '10,936,000,000원', '8,217,000,000원', '7,088,000,000원', '6,620,000,000원']

       종목     등락률    총 거래량            총 거래액
1    엘앤에프  +6.01%  130,000  21,557,000,000원
2  에코프로비엠  +4.96%   28,000  10,936,000,000원
3  셀트리온제약  +3.69%   67,000   8,217,000,000원
4    네이처셀  -8.60%  326,000   7,088,000,000원
5  티케이케미칼  -2.92%  999,000   6,620,000,000원
********************************************************************************
['삼성전자', '카카오', 'NAVER', 'KODEX 레버리지', '현대차']
['+0.42%', '-0.84%', '-0.64%', '+0.33%', '+1.99%']
['1,391,000', '604,000', '132,000', '2,047,000', '223,000']
['99,893,000,000원', '71,327,000,000원', '51,595,000,000원', '46,707,000,000원', '44,421,000,000원']

           종목     등락률      총 거래량            총 거래액
1        삼성전자  +0.42%  1,391,000  99,893,000,000원
2         카카오  -0.84%    604,000  71,327,000,000원
3       NAVER  -0.64%    132,000  51,595,000,000원
4  KODEX 레버리지  +0.33%  2,047,000  46,707,000,000원
5         현대차  +1.99%    223,000  44,421,000,000원
********************************************************************************
['CJ ENM', '카카오게임즈', '펄어비스', '스튜디오드래곤', '싸이토젠']
['+0.94%', '-2.97%', '-2.21%', '+0.32%', '+0.65%']
['171,000', '142,000', '94,000', '55,000', '65,000']
['29,090,000,000원', '9,409,000,000원', '8,391,000,000원', '5,076,000,000원', '3,966,000,000원']

        종목     등락률    총 거래량            총 거래액
1   CJ ENM  +0.94%  171,000  29,090,000,000원
2   카카오게임즈  -2.97%  142,000   9,409,000,000원
3     펄어비스  -2.21%   94,000   8,391,000,000원
4  스튜디오드래곤  +0.32%   55,000   5,076,000,000원
5     싸이토젠  +0.65%   65,000   3,966,000,000원
********************************************************************************
['KODEX 200선물인버스2X', '대유에이텍', 'KODEX 인버스', '우신시스템', 'KODEX 코스닥150선물인버스']
['2,305', '1,800', '4,130', '7,140', '4,470']
['121,798,253', '28,104,245', '21,651,763', '21,299,615', '16,600,383']
['▼10', '▲50', '▼5', '▲1,360', '▲10']
['-0.43%', '+2.86%', '-0.12%', '+23.53%', '+0.22%']

                  종목     가격    등락가격      등락률          거래량
1   KODEX 200선물인버스2X  2,305     ▼10   -0.43%  121,798,253
2              대유에이텍  1,800     ▲50   +2.86%   28,104,245
3          KODEX 인버스  4,130      ▼5   -0.12%   21,651,763
4              우신시스템  7,140  ▲1,360  +23.53%   21,299,615
5  KODEX 코스닥150선물인버스  4,470     ▲10   +0.22%   16,600,383
********************************************************************************
['티비씨', '바른손이앤에이', '바른손', '쇼박스', '에이비프로바이오']
['2,225', '1,620', '4,495', '6,180', '1,250']
['48,130,262', '25,081,364', '23,737,884', '23,655,042', '20,288,062']
['▲290', '▲80', '▲785', '▼250', '▲50']
['+14.99%', '+5.19%', '+21.16%', '-3.89%', '+4.17%']

         종목     가격  등락가격      등락률         거래량
1       티비씨  2,225  ▲290  +14.99%  48,130,262
2   바른손이앤에이  1,620   ▲80   +5.19%  25,081,364
3       바른손  4,495  ▲785  +21.16%  23,737,884
4       쇼박스  6,180  ▼250   -3.89%  23,655,042
5  에이비프로바이오  1,250   ▲50   +4.17%  20,288,062
********************************************************************************
['삼성전자', 'SK하이닉스', 'NAVER', '삼성전자우', '삼성바이오로직스']
['71,900', '93,800', '391,000', '66,400', '824,000']
['4,298,243', '682,866', '641,449', '546,397', '545,861']
['▲300', '▼1,900', '▼2,500', '▲800', '▲9,000']
['+0.42%', '-1.99%', '-0.64%', '+1.22%', '+1.10%']

         종목       가격    등락가격     등락률        거래량
1      삼성전자   71,900    ▲300  +0.42%  4,298,243
2    SK하이닉스   93,800  ▼1,900  -1.99%    682,866
3     NAVER  391,000  ▼2,500  -0.64%    641,449
4     삼성전자우   66,400    ▲800  +1.22%    546,397
5  삼성바이오로직스  824,000  ▲9,000  +1.10%    545,861
********************************************************************************
['셀트리온헬스케어', '에코프로비엠', '엘앤에프', '펄어비스', '에이치엘비']
['89,800', '431,600', '183,400', '88,700', '52,900']
['138,432', '93,903', '62,760', '58,275', '55,757']
['▲3,100', '▲20,400', '▲10,400', '▼2,000', '▲2,400']
['+3.58%', '+4.96%', '+6.01%', '-2.21%', '+4.75%']

         종목       가격     등락가격     등락률      거래량
1  셀트리온헬스케어   89,800   ▲3,100  +3.58%  138,432
2    에코프로비엠  431,600  ▲20,400  +4.96%   93,903
3      엘앤에프  183,400  ▲10,400  +6.01%   62,760
4      펄어비스   88,700   ▼2,000  -2.21%   58,275
5     에이치엘비   52,900   ▲2,400  +4.75%   55,757
********************************************************************************

In [28]:
for i in ranks[3:]:html=driver.page_source
soup=bs(html,'html.parser')
ranks=soup.find_all('div',class_="halfB")
kos=['코스피','코스닥']
num=[1,2,3,4,5]

for i in (ranks[3:]):
    if i in ranks[7:11]:
        m_name=[]
        m_price=[]
        m_amount=[]
        m_updown=[]
        name=(i.select_one('ul').select('a'))
        updown=(i.select_one('ul').select('span')[1::2])
        amount=(i.select_one('ul').select('span')[0::2])
        price=(i.select_one('ul').select('p'))
        for a in name:
            m_name.append(a.text)
        for s in updown:
            m_updown.append(s.text)
        for d in amount:
            m_amount.append(d.text+',000')
        for f in price:
            m_price.append(f.text+',000,000원')
        list=[]
        for i in range(5):
            list.append([m_name[i],m_updown[i],m_amount[i],m_price[i]])
    
        
        print(m_name)
        print(m_updown)
        print(m_amount)
        print(m_price)
        print(list)
        print()
        chart=pd.DataFrame(list,columns=['종목','등락률','총 거래량','총 거래액'],index=num)
        print(chart)

['기아', 'SK바이오사이언스', '한국가스공사', '일진머티리얼즈', 'SK케미칼']
['+2.76%', '0.00%', '-0.52%', '+3.47%', '+4.97%']
['280,000', '92,000', '424,000', '198,000', '59,000']
['21,734,000,000원', '21,037,000,000원', '19,831,000,000원', '19,637,000,000원', '16,751,000,000원']
[['기아', '+2.76%', '280,000', '21,734,000,000원'], ['SK바이오사이언스', '0.00%', '92,000', '21,037,000,000원'], ['한국가스공사', '-0.52%', '424,000', '19,831,000,000원'], ['일진머티리얼즈', '+3.47%', '198,000', '19,637,000,000원'], ['SK케미칼', '+4.97%', '59,000', '16,751,000,000원']]

          종목     등락률    총 거래량            총 거래액
1         기아  +2.76%  280,000  21,734,000,000원
2  SK바이오사이언스   0.00%   92,000  21,037,000,000원
3     한국가스공사  -0.52%  424,000  19,831,000,000원
4    일진머티리얼즈  +3.47%  198,000  19,637,000,000원
5      SK케미칼  +4.97%   59,000  16,751,000,000원
['엘앤에프', '에코프로비엠', '셀트리온제약', '네이처셀', '티케이케미칼']
['+6.88%', '+5.33%', '+3.77%', '-8.60%', '-2.63%']
['130,000', '28,000', '67,000', '326,000', '999,000']
['21,557,000,000원', '10,936,000,000원', '8,217,000,000원', '7,088,000,000원', '6,620,000,000원']
[['엘앤에프', '+6.88%', '130,000', '21,557,000,000원'], ['에코프로비엠', '+5.33%', '28,000', '10,936,000,000원'], ['셀트리온제약', '+3.77%', '67,000', '8,217,000,000원'], ['네이처셀', '-8.60%', '326,000', '7,088,000,000원'], ['티케이케미칼', '-2.63%', '999,000', '6,620,000,000원']]

       종목     등락률    총 거래량            총 거래액
1    엘앤에프  +6.88%  130,000  21,557,000,000원
2  에코프로비엠  +5.33%   28,000  10,936,000,000원
3  셀트리온제약  +3.77%   67,000   8,217,000,000원
4    네이처셀  -8.60%  326,000   7,088,000,000원
5  티케이케미칼  -2.63%  999,000   6,620,000,000원
['삼성전자', '카카오', 'NAVER', 'KODEX 레버리지', '현대차']
['+0.56%', '-0.84%', '-0.64%', '+0.46%', '+1.74%']
['1,391,000', '604,000', '132,000', '2,047,000', '223,000']
['99,893,000,000원', '71,327,000,000원', '51,595,000,000원', '46,707,000,000원', '44,421,000,000원']
[['삼성전자', '+0.56%', '1,391,000', '99,893,000,000원'], ['카카오', '-0.84%', '604,000', '71,327,000,000원'], ['NAVER', '-0.64%', '132,000', '51,595,000,000원'], ['KODEX 레버리지', '+0.46%', '2,047,000', '46,707,000,000원'], ['현대차', '+1.74%', '223,000', '44,421,000,000원']]

           종목     등락률      총 거래량            총 거래액
1        삼성전자  +0.56%  1,391,000  99,893,000,000원
2         카카오  -0.84%    604,000  71,327,000,000원
3       NAVER  -0.64%    132,000  51,595,000,000원
4  KODEX 레버리지  +0.46%  2,047,000  46,707,000,000원
5         현대차  +1.74%    223,000  44,421,000,000원
['CJ ENM', '카카오게임즈', '펄어비스', '스튜디오드래곤', '싸이토젠']
['+1.06%', '-2.97%', '-1.87%', '+0.75%', '+0.65%']
['171,000', '142,000', '94,000', '55,000', '65,000']
['29,090,000,000원', '9,409,000,000원', '8,391,000,000원', '5,076,000,000원', '3,966,000,000원']
[['CJ ENM', '+1.06%', '171,000', '29,090,000,000원'], ['카카오게임즈', '-2.97%', '142,000', '9,409,000,000원'], ['펄어비스', '-1.87%', '94,000', '8,391,000,000원'], ['스튜디오드래곤', '+0.75%', '55,000', '5,076,000,000원'], ['싸이토젠', '+0.65%', '65,000', '3,966,000,000원']]

        종목     등락률    총 거래량            총 거래액
1   CJ ENM  +1.06%  171,000  29,090,000,000원
2   카카오게임즈  -2.97%  142,000   9,409,000,000원
3     펄어비스  -1.87%   94,000   8,391,000,000원
4  스튜디오드래곤  +0.75%   55,000   5,076,000,000원
5     싸이토젠  +0.65%   65,000   3,966,000,000원

In [29]:
def dt():
    soup=bs(html,'html.parser')
    ranks=soup.find_all('div',class_="halfB")
    kos=['코스피','코스닥']
    num=[1,2,3,4,5]

    for i in (ranks[3:]):
        if i in ranks[7:11]:
            m_name=[]
            m_price=[]
            m_amount=[]
            m_updown=[]
            name=(i.select_one('ul').select('a'))
            updown=(i.select_one('ul').select('span')[1::2])
            amount=(i.select_one('ul').select('span')[0::2])
            price=(i.select_one('ul').select('p'))
            for a in name:
                m_name.append(a.text)
            for s in updown:
                m_updown.append(s.text)
            for d in amount:
                m_amount.append(d.text+',000')
            for f in price:
                m_price.append(f.text+',000,000원')
            list=[]
            for i in range(5):
                list.append([m_name[i],m_updown[i],m_amount[i],m_price[i]])


            print(m_name)
            print(m_updown)
            print(m_amount)
            print(m_price)
            print(list)
            print()
            chart=pd.DataFrame(list,columns=['종목','등락률','총 거래량','총 거래액'],index=num)
            print(chart)
            return chart

dt()

['기아', 'SK바이오사이언스', '한국가스공사', '일진머티리얼즈', 'SK케미칼']
['+2.76%', '0.00%', '-0.52%', '+3.47%', '+4.97%']
['280,000', '92,000', '424,000', '198,000', '59,000']
['21,734,000,000원', '21,037,000,000원', '19,831,000,000원', '19,637,000,000원', '16,751,000,000원']
[['기아', '+2.76%', '280,000', '21,734,000,000원'], ['SK바이오사이언스', '0.00%', '92,000', '21,037,000,000원'], ['한국가스공사', '-0.52%', '424,000', '19,831,000,000원'], ['일진머티리얼즈', '+3.47%', '198,000', '19,637,000,000원'], ['SK케미칼', '+4.97%', '59,000', '16,751,000,000원']]

          종목     등락률    총 거래량            총 거래액
1         기아  +2.76%  280,000  21,734,000,000원
2  SK바이오사이언스   0.00%   92,000  21,037,000,000원
3     한국가스공사  -0.52%  424,000  19,831,000,000원
4    일진머티리얼즈  +3.47%  198,000  19,637,000,000원
5      SK케미칼  +4.97%   59,000  16,751,000,000원

          종목     등락률    총 거래량            총 거래액
1         기아  +2.76%  280,000  21,734,000,000원
2  SK바이오사이언스   0.00%   92,000  21,037,000,000원
3     한국가스공사  -0.52%  424,000  19,831,000,000원
4    일진머티리얼즈  +3.47%  198,000  19,637,000,000원
5      SK케미칼  +4.97%   59,000  16,751,000,000원